/* AUTO-GENERATED FILE. DO NOT MODIFY.
*
* This class was automatically generated by the
* aapt tool from the resource data it found. It
* should not be modified by hand.
*/
package mod.tsd.activities;

public final class R {
public static final class drawable {
public static final int app_icon=0x7f020000;
public static final int default_image=0x7f020001;
public static final int girl_swimming_flat=0x7f020002;
public static final int ic_arrow_drop_down_black=0x7f020003;
public static final int ic_arrow_drop_up_black=0x7f020004;
}
public static final class id {
public static final int Log=0x7f030000;
public static final int Main=0x7f030001;
public static final int hscroll1=0x7f030002;
public static final int imageview1=0x7f030003;
public static final int linear1=0x7f030004;
public static final int linear2=0x7f030005;
public static final int linear3=0x7f030006;
public static final int textview1=0x7f030007;
public static final int textview2=0x7f030008;
public static final int vscroll1=0x7f030009;
}
public static final class layout {
public static final int documentation=0x7f040000;
public static final int documentation_adapter=0x7f040001;
public static final int documention_adapter=0x7f040002;
public static final int main=0x7f040003;
}
}
